import type { Metadata } from "next";
import { Inter } from "next/font/google"; // 1. Use standard font
import "./globals.css";

// 2. Configure standard font
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 3. Apply standard font class */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
